import scrapy
from scrapy.loader.processors import MapCompose, TakeFirst
from w3lib.html import remove_tags


class Party(scrapy.Item):
    title = scrapy.Field(input_processor=MapCompose(str.strip))
    short_name = scrapy.Field(input_processor=MapCompose(str.strip))
    eligible_dt = scrapy.Field(input_processor=MapCompose(str.strip))
    registered_dt = scrapy.Field(input_processor=MapCompose(str.strip))
    deregistered_dt = scrapy.Field(input_processor=MapCompose(str.strip))
    leader = scrapy.Field()
    logo = scrapy.Field(
        input_processor=MapCompose(lambda path: f"https://www.elections.ca{path}")
    )
    website = scrapy.Field()
    national_hq_address_line_1 = scrapy.Field()
    national_hq_address_line_2 = scrapy.Field()
    national_hq_address_line_3 = scrapy.Field()
    national_hq_address_line_4 = scrapy.Field()
    national_hq_city = scrapy.Field()
    national_hq_prov = scrapy.Field()
    national_hq_postal_code = scrapy.Field()
    national_hq_phone = scrapy.Field()
    national_hq_fax = scrapy.Field()
    chief_agent_address_line_1 = scrapy.Field()
    chief_agent_address_line_2 = scrapy.Field()
    chief_agent_address_line_3 = scrapy.Field()
    chief_agent_address_line_4 = scrapy.Field()
    chief_agent_address_line_5 = scrapy.Field()
    chief_agent_city = scrapy.Field()
    chief_agent_prov = scrapy.Field()
    chief_agent_postal_code = scrapy.Field()
    chief_agent_phone = scrapy.Field()
    chief_agent_fax = scrapy.Field()
    auditor_address_line_1 = scrapy.Field()
    auditor_address_line_2 = scrapy.Field()
    auditor_address_line_3 = scrapy.Field()
    auditor_address_line_4 = scrapy.Field()
    auditor_city = scrapy.Field()
    auditor_prov = scrapy.Field()
    auditor_postal_code = scrapy.Field()
    auditor_phone = scrapy.Field()
    auditor_fax = scrapy.Field()
